### ISSUE TITLE
Add a progress bar

### ISSUE THREAD

**Issue by pjsier** [pjsier/aggspread#3]
Adding some indication of progress could be a nice-to-have here. It looks like [`pb`](https://github.com/cheggaaa/pb) or [`progressbar`](https://github.com/schollz/progressbar) could work.

The progress bar could be created before `MakeSpreaders` is called and use the number of features in the feature collection as the basis for completion. Because invalid features are ignored, it should complete once the channel is closed regardless of the count. It would need to write to stderr or not run at all if the output is stdout.

**Comment by VictorAssunc** [comment]
I would like to work on it 😄

**Comment by pjsier** [comment]
@VictorAssunc sounds great! Assigning you now, feel free to post any questions or issues you run into here

**Comment by VictorAssunc** [comment]
Thank you. @pjsier . Would you have some files for testing?

**Comment by pjsier** [comment]
Sure! Here's a gist you can use of turnout by voting precinct in Chicago https://gist.github.com/pjsier/cb2e554e55726de9b0cd79602272fe6a

Any of the fields that start with `votes_` or `voters_` like `voters_20` should work @VictorAssunc
